version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/productApp
      - SPRING_DATASOURCE_USERNAME=productApp
      - SPRING_DATASOURCE_PASSWORD=productApp
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/productApp
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/management/health']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  postgresql:
    image: postgres:17.4
    environment:
      - POSTGRES_DB=productApp
      - POSTGRES_USER=productApp
      - POSTGRES_PASSWORD=productApp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U productApp']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
